#!/usr/bin/env bash

# see https://stackoverflow.com/questions/592620/how-to-check-if-a-program-exists-from-a-bash-script
command -v pactl >/dev/null 2>&1 || { echo >&2 "Require pactl but it's not installed.  Aborting."; exit 1; }

case $1 in
	"up")
		INDICATOR="+"
		;;
	"down")
		INDICATOR="-"
		;;
	*)
		echo "usage: updown-volume [up|down] [0-9]"
		exit 1
esac

for SINK in `pactl list short sinks | awk '{print $1}'`
do              
	pactl set-sink-volume $SINK $INDICATOR$2%
done
exit 0
